version: '3.8'

services:
  app:
    image: php:8.2-apache
    volumes:
      - ./src:/var/www/html

  nginx:
    image: nginx:latest
    ports:
      - '9999:9999'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

networks:
  default:
    driver: bridge
    name: php-easy-onboarding
