version: '3.8'

services:
  db:
    image: postgres:16.2-alpine
    restart: always
    environment:
      - PORGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  app:
    image: php:8.2-apache
    volumes:
      - ./:/var/www/html

  nginx:
    image: nginx:latest
    ports:
      - '9999:9999'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

networks:
  default:
    driver: bridge
    name: php-easy-onboarding
